dist: Xenial
language: c

before_install:
    - apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 6B05F25D762E3157 || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt update -y
    - sudo apt install g++-7 -y
    - sudo apt install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev -y
    - sudo apt-get install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi -y
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . -- -j`nproc`
  - cd ..
  - ./launchTest.sh
  - cp build/coverage/*.gc* .
  - gcov *.gcno

env:
  global:
    - CODECOV_TOKEN=f364999a-5f28-463b-9249-28da928e70c1

after_success:
  - bash <(curl -s https://codecov.io/bash)
