dist: Xenial
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libc6-armel-cross
      - libc6-dev-armel-cross
      - binutils-arm-linux-gnueabi 
      - libncurses5-dev

before_install:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . -- -j`nproc`