dist: Xenial
language: c

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt update -y
    - sudo apt install g++-7 -y
    - sudo apt install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev -y
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . -- -j`nproc`